### PR TITLE
Always import the `RawBytes` module qualified

### PR DESCRIPTION
**Pull request by jorisdral**

### CODE REVIEW

**Review by mheinzel — APPROVED** [review]
There's a little bit of tension between choosing identifiers that work well when imported qualified and on the other hand going for similarity to the primitive vector API, e.g. `sizeofRawBytes` could just be `size`.
Still makes sense overall I think.

**Review by phadej — CHANGES_REQUESTED** [review]
> There's a little bit of tension between choosing identifiers that work well when imported qualified and on the other hand going for similarity to the primitive vector API, e.g. `sizeofRawBytes` could just be `size`. Still makes sense overall I think.

Indeed.

- `sizeofRawBytes` -> `size`
- `rawBytes` -> `builder` or `toBuilder`
-  `takeRawBytes` -> `take`
- `hashRawBytes` -> `hash`
- `mkRawBytes` -> `fromByteArray`

And I insist that the renaming is done simultaneously, as it will touch most of the same use-sites as importing qualified.

**Comment by phadej** [comment]
```haskell
{- | This module is intended to be imported qualified, to avoid name clashes with "Prelude" functions, e.g.

@
 import           Database.LSMTree.Internal.Serialise.RawBytes (RawBytes)
 import qualified Database.LSMTree.Internal.Serialise.RawBytes as RB
@
-}
module Database.LSMTree.Internal.Serialise.RawBytes (
    ..
```

**Comment by jorisdral** [comment]
@phadej @mheinzel valid feedback. I've updated the PR, let me know what you think

**Comment by mheinzel** [comment]
Looks good to me.

**Pull request merged**
