### PR TITLE
Add rangeLookup implementation for Data.Map

### PR DESCRIPTION
**Pull request by phadej**
To be used in model implementation

### CODE REVIEW

**Comment by phadej** [comment]
I think build (9.4.6, 3.10.1.0, ...) jobs are not yet configured but already required, so this PR is in the weird state.

**Comment by jorisdral** [comment]
After #2 is merged, the workflow file should be updated to include the `ghc-9.4.6`/`cabal-3.10.1.0` job

**Review by dcoutts — APPROVED** [review]
This looks fine, and the tests look reliable.

I do wonder however if the range lookup could be done more elegantly using existing functions from the public API, rather than going directly to the internals. There's `spanAntitone` and `drop/takeWhileAntitone` which look like they'd do what we want.

**Comment by phadej** [comment]
*more elegantly* for sure, but it will do more work constructing intermediate maps.

**Pull request merged**
